# Generated by Django 5.0.4 on 2024-05-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200, null=True)),
                ('time_order', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('experience', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('stars', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=40, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('hotel_rating', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('person_rating', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_card_number', models.IntegerField(null=True)),
                ('serial', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_app.user')),
                ('owner_exp_status', models.IntegerField(null=True)),
            ],
            bases=('booking_app.user',),
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_app.user')),
                ('guest_rating', models.IntegerField(null=True)),
            ],
            bases=('booking_app.user',),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name'], name='first_name_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['age'], name='age_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['sex'], name='sex_idx'),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='owners',
            field=models.ManyToManyField(related_name='hobbies', to='booking_app.user'),
        ),
        migrations.AddField(
            model_name='bookorderinfo',
            name='hotels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_info', to='booking_app.hotels'),
        ),
        migrations.AddField(
            model_name='hotelscomment',
            name='hotels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.hotels'),
        ),
        migrations.AddField(
            model_name='personcomment',
            name='hotels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_comments', to='booking_app.hotels'),
        ),
        migrations.AddField(
            model_name='profile',
            name='persons',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='booking_app.user'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='owners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='booking_app.hotelowner'),
        ),
        migrations.AddField(
            model_name='personcomment',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_comments', to='booking_app.persons'),
        ),
        migrations.AddField(
            model_name='hotelscomment',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.persons'),
        ),
        migrations.AddField(
            model_name='bookorderinfo',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_info', to='booking_app.persons'),
        ),
    ]
