# Generated by Django 5.0.4 on 2024-05-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
