# Generated by Django 5.0.4 on 2024-05-10 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_hotels_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200, null=True)),
                ('time_order', models.DateTimeField(auto_now_add=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_info', to='booking_app.hotels')),
                ('persons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_info', to='booking_app.persons')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('experience', models.IntegerField(null=True)),
                ('persons', models.ManyToManyField(related_name='hobbies', to='booking_app.persons')),
                ('owners', models.ManyToManyField(related_name='hobbies', to='booking_app.hotelowner')),
            ],
        ),
        migrations.AddField(
            model_name='hotels',
            name='owners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='booking_app.hotelowner'),
        ),
        migrations.CreateModel(
            name='HotelsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('time_comment', models.DateTimeField(auto_now_add=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.hotels')),
                ('persons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.persons')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_card_number', models.IntegerField(null=True)),
                ('serial', models.FloatField(null=True)),
                ('hotel_owners', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='booking_app.hotelowner')),
                ('persons', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='booking_app.persons')),
            ],
        ),
    ]
